 {
  "variables": {
		"bullet_dir%": "../third_party/bullet"
  },
  
  'targets': [
    {
      'target_name': 'bulletCpuDemos',
      'type': 'executable',
      'dependencies': [ 'bullet' ],
      'sources': [ '<(bullet_dir)/Demos/AllBulletDemos/DemoEntries.cpp',
				   '<(bullet_dir)/Demos/AllBulletDemos/Main.cpp',
	  ],
	  'libraries': [
		'-l<(bullet_dir)/Glut/glut32.lib',
      ],
      'include_dirs': [
        '<(bullet_dir)/src/',
        '<(bullet_dir)/Demos/',
        '<(bullet_dir)/Glut/',
        '<(bullet_dir)/Extras/',
        '<(bullet_dir)/Demos/OpenGL',
      ],
      "target_conditions": [
		["OS == 'win'", {
		  "defines": [
			"GLUT_FOUND",
		  ]
		}]
	  ],
    },
    {
      'target_name': 'bullet',
      'type': 'shared_library',
      'sources': [
        #Bullet multithreaded
        '<(bullet_dir)/src/BulletMultiThreaded/SpuCollisionObjectWrapper.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuSampleTask/SpuSampleTask.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuLibspe2Support.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuContactResult.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuGatheringCollisionTask.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuMinkowskiPenetrationDepthSolver.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/SpuCollisionShapes.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/btThreadSupportInterface.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SequentialThreadSupport.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuGatheringCollisionDispatcher.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/Win32ThreadSupport.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuFakeDma.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/PosixThreadSupport.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuCollisionTaskProcess.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuContactManifoldCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuSampleTaskProcess.cpp',
        '<(bullet_dir)/src/BulletMultiThreaded/SpuNarrowPhaseCollisionTask/boxBoxDistance.cpp',
        # Linear math
        '<(bullet_dir)/src/LinearMath/btQuickprof.cpp',
        '<(bullet_dir)/src/LinearMath/btGeometryUtil.cpp',
        '<(bullet_dir)/src/LinearMath/btAlignedAllocator.cpp',
        '<(bullet_dir)/src/LinearMath/btSerializer.cpp',
        '<(bullet_dir)/src/LinearMath/btConvexHull.cpp',
        '<(bullet_dir)/src/LinearMath/btPolarDecomposition.cpp',
        '<(bullet_dir)/src/LinearMath/btVector3.cpp',
        '<(bullet_dir)/src/LinearMath/btConvexHullComputer.cpp',
        # Bullet collision
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp',
        '<(bullet_dir)/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btGhostObject.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btUnionFind.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btShapeHull.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btCompoundShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConeShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btSphereShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btEmptyShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btCollisionShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConcaveShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btBoxShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btBox2dShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btCylinderShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp',
        '<(bullet_dir)/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btDbvt.cpp',
        '<(bullet_dir)/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/btGImpactBvh.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/btGImpactShape.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/gim_box_set.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/gim_contact.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/gim_memory.cpp',
        '<(bullet_dir)/src/BulletCollision/Gimpact/gim_tri_collision.cpp',
        # Bullet dynamics
	'<(bullet_dir)/src/BulletDynamics/Dynamics/btRigidBody.cpp',
        '<(bullet_dir)/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp',
        '<(bullet_dir)/src/BulletDynamics/Dynamics/Bullet-C-API.cpp',
        '<(bullet_dir)/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp',
        '<(bullet_dir)/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp',
        '<(bullet_dir)/src/BulletDynamics/Vehicle/btWheelInfo.cpp',
        '<(bullet_dir)/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp',
        '<(bullet_dir)/src/BulletDynamics/Character/btKinematicCharacterController.cpp',
        #Soft body
        '<(bullet_dir)/src/BulletSoftBody/btDefaultSoftBodySolver.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftBody.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftRigidDynamicsWorld.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftBodyHelpers.cpp',
        '<(bullet_dir)/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp',
     ],
        'include_dirs': [
          '<(bullet_dir)/src/',
        ],
        'all_dependent_settings': {
          'include_dirs': [
            '<(bullet_dir)/src/',
        ],
        },
    },
  ],
}
