 {
    "variables": {
        "polycode_dir%": "../../Polycode/"
    },
    'targets': [
      {
        'target_name': 'polycode',
        'type': 'executable',
        'dependencies': [
          'zlib.gyp:zlib',
          'libpng.gyp:libpng',
          'freetype.gyp:freetype',
          'lua.gyp:lua',
	      'physfs.gyp:physfs',
		  'libogg.gyp:ogg',
		  'libvorbis.gyp:libvorbis',
		  'openal-soft.gyp:OpenAL32',
		  'sdl2.gyp:SDL2',
		  'box2d.gyp:box2d',
		  'bullet.gyp:bullet',
		  'assimp.gyp:assimp',
		  'glext.gyp:glext_download',
		  'wglext.gyp:wglext_download',
        ],
        'sources': [
          '<(polycode_dir)/Core/Contents/Source/OSBasics.cpp',
		  '<(polycode_dir)/Core/Contents/Source/PolyBezierCurve.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyBone.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyCamera.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyColor.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyConfig.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyCore.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyCoreInput.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyCoreServices.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyCubemap.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyData.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyEntity.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyEvent.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyEventDispatcher.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyEventHandler.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyFixedShader.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyFont.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyFontManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLCubemap.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLRenderer.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLSLProgram.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLSLShader.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLSLShaderModule.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLTexture.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyGLVertexBuffer.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyImage.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyInputEvent.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyLabel.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyLogger.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyMaterial.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyMaterialManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyMatrix4.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyMesh.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyModule.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyObject.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyParticle.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyParticleEmitter.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyPerlin.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyPolygon.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyQuaternion.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyQuaternionCurve.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyRectangle.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyRenderer.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyResource.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyResourceManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScene.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneEntity.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneLabel.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneLight.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneLine.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneMesh.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScenePrimitive.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneRenderTexture.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySceneSound.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreen.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenEntity.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenEvent.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenImage.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenLabel.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenLine.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenMesh.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenShape.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenSound.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenSprite.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyScreenEntityInstance.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyShader.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySkeleton.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySound.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySoundManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyString.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyTexture.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyThreaded.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyTimer.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyTimerManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyTween.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyTweenManager.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyVector2.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyVector3.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyVertex.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/tinystr.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/tinyxml.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/tinyxmlerror.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/tinyxmlparser.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolySocket.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyPeer.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyClient.cpp',
    	  '<(polycode_dir)/Core/Contents/Source/PolyServer.cpp',
    	],
    	'include_dirs': [
    	  '<(polycode_dir)/Core/Contents/Include/',
    	  '../third_party/glext/',
        ],
         'conditions': [
         ['OS=="win"', {
           'source_files': [
              '<(polycode_dir)/Core/Contents/PolycodeView/MSVC/PolycodeView.cpp', 
              '<(polycode_dir)/Core/Contents/Source/PolyWinCore.cpp',
           ],
           'include_dirs': [
             '<(polycode_dir)/Core/Contents/PolycodeView/MSVC/',
           ],
           'defines': [
             '_WINDOWS',
           ], }
         ],
         ['OS=="osx"', {
           'source_files': [
             '<(polycode_dir)/Core/Contents/PolycodeView/Mac OS X/PolycodeView.mm', 
           ],
           'include_dirs': [
             '<(polycode_dir)/Core/Contents/PolycodeView/Mac OS X/',
             ],
		   }
         ],
         ['OS=="linux"', {
           'source_files': [
             '<(polycode_dir)/Core/Contents/PolycodeView/Linux/PolycodeView.cpp',
             '/usr/include/X11/', 
           ],
           'include_dirs': [
             '<(polycode_dir)/Core/Contents/PolycodeView/Linux/',
             ],
		   }
         ],
     ],   
  }, ],
}
